name: Sync main branch to friend's repo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Push to friend's repo without workflows
        env:
          MIRROR_TOKEN: ${{ secrets.MIRROR_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout -b mirror-branch
          git rm -r --cached .github/
          git commit -m "Mirror sync (excluding workflows)"
          git remote add mirror https://x-access-token:${MIRROR_TOKEN}@github.com/ReMedia-Agency/remediasite.git
          git push mirror mirror-branch:main --force
